### ISSUE TITLE
Неверное расписание при наличии выходного в середине недели

### ISSUE THREAD

**Issue by tipapro** [takeonfaith/LK#13]
Из-за выходного дня в середине недели json возвращается без ключа этого дня.
![изображение](https://user-images.githubusercontent.com/17129060/147238417-3ce2710b-a9c3-4f1a-a99d-0a50e76b71ab.png)

В итоге это приводит к выводу на текущий выходной день расписания следующего дня

### Возможное решение:

Либо добавлять пропущенный день вручную тут:
https://github.com/takeonfaith/LK/blob/10c20e841d607080625333d37892f11d3d31da1e/src/entities/schedule/model/index.ts#L18

Либо менять проверку тут:
https://github.com/takeonfaith/LK/blob/ed61e454033f6ac4abb6b55f08b3ead89fd450dd/src/features/home/ui/organisms/schedule-and-notification.tsx#L14

**Comment by takeonfaith** [comment]
Окей, спасибо, пофиксим

**Comment by tipapro** [comment]
### Дополнение:
Эта ошибка полностью крашит экран расписания и на главном экране съезжают все дни дальше. То есть на пятницу показывается расписание на субботу
