### ISSUE TITLE
Белый экран при открытии "Расписание"

### ISSUE THREAD

**Issue by dansibleadm** [takeonfaith/LK#21]
OS: Windows 10
Браузер: Google Chrome Version 97.0.4692.71 (Official Build) (64-bit)

При попытке открыть раздел "Расписание" ничего не происходит, только белый экран.
В консоли есть такие ошибки.
![image](https://user-images.githubusercontent.com/39000316/150357964-859daf94-43de-48d4-bcec-71e5fa03ec12.png)

**Comment by takeonfaith** [comment]
Привет. Расскажи, пожалуйста, чуть подробнее. Какое расписание в теории тебе должно приходить? В плане, есть ли у тебя расписание за семестр все еще (проверь rasp.dmami), и есть ли у тебя уже расписание сессии(на rasp.dmami/session)? И еще: зайди в Network и, пж, покажи, какой результат обращения к эндпоинту /getSchedule и /getSchedule&session=1. Раскрой, если есть, что раскрыть, хотя бы один пришедший объект из двух этих апи

**Comment by dansibleadm** [comment]
1. Расписание сессии есть
2. Таких эндпоинтов нет. Только giphy.gif
3. Удалось получить эти эндпоинты только после Ctrl+Shift+R:
В getSchedule&session=1<SNIP> json-нина с расписанием: 
![image](https://user-images.githubusercontent.com/39000316/150405040-9353de42-5088-491e-a92c-e6ce91e149e8.png)

**Comment by tipapro** [comment]
Возможно причина в том, что тут нет поддержки 19:30-21:00 (как и ниже в этом же файле)
https://github.com/takeonfaith/LK/blob/3905d203b24555f6fe045908dbc4ed97a169c7c0/src/shared/api/model/schedule.ts#L9

Что приводит к ошибке тут
https://github.com/takeonfaith/LK/blob/3905d203b24555f6fe045908dbc4ed97a169c7c0/src/features/schedule/ui/atoms/subject.tsx#L77

И если в лк также, как и в rasp.dmami.ru, то есть ещё время вечерников для 6 и 7 пар

**Comment by takeonfaith** [comment]
Ага, это хорошее предположение, он на этом действительно должен ломаться. Спасибо
