### ISSUE TITLE
Неполная информация о приказах

### ISSUE THREAD

**Issue by dansibleadm** [takeonfaith/LK#22]
Ну, собственно, смотри картинку.
![image](https://user-images.githubusercontent.com/39000316/150405251-698215bc-1746-473c-ad6a-1cd37fd104b5.png)

Что должно быть:
![image](https://user-images.githubusercontent.com/39000316/150405347-7e5429dc-1532-42e3-b4b1-3dd5aae180fb.png)

**Comment by skaele** [comment]
Проблема в данных, которые возвращает апишка, уже попросили пофиксить, спасибо
