### ISSUE TITLE
Не грузиться странница оплаты

### ISSUE THREAD

**Issue by dansibleadm** [takeonfaith/LK#23]
Зависает на гифке загрузки и на этом все:
![image](https://user-images.githubusercontent.com/39000316/150405527-252d98cb-001a-4dd7-bdf2-f5c9683fbd9d.png)

**Comment by takeonfaith** [comment]
Опять же, нужно знать, какие данные приходят, просто по скрину сказать сложно, в чем проблема. Сделай, пж, скрин с Network'a и результата обращения к апи

**Comment by dansibleadm** [comment]
Приходит ничего (ожидаемые данные, так как я не платник). Однако на мой взгляд хорошо бы выводить что-то, а не грузящуюся гифку
![image](https://user-images.githubusercontent.com/39000316/150510926-6fd4147d-b3e5-4168-9cf7-e6d6158f2ec4.png)

**Comment by takeonfaith** [comment]
Вот, это уже действительно полезная инфа. Спасибо, исправим
